"use client";

import React, { createContext, useContext } from "react";

export type LeaderboardItem = {
  rank: number;
  slug: string;
  name: string;
  founder: string;
  mrr: string;
  trust_score: number;
};

export type StartupCard = {
  initials: string;
  name: string;
  category: string;
  description: string;
  mrr: string;
  growth: string;
  badge: string;
  slug: string;
};

export interface HomepageInitialData {
  leaderboard: LeaderboardItem[];
  recentlyListedData: StartupCard[];
  trendingData: StartupCard[];
  verifiedStartupCount: number;
  verifiedRevenueTotal: number;
}

interface StartupDataContextType {
  leaderboard: LeaderboardItem[];
  recentlyListedData: StartupCard[];
  trendingData: StartupCard[];
  verifiedStartupCount: number;
  verifiedRevenueTotal: number;
  loading: boolean;
  error: string | null;
}

const StartupDataContext = createContext<StartupDataContextType>({
  leaderboard: [],
  recentlyListedData: [],
  trendingData: [],
  verifiedStartupCount: 0,
  verifiedRevenueTotal: 0,
  loading: false,
  error: null,
});

export function useStartupData() {
  return useContext(StartupDataContext);
}

/**
 * StartupDataProvider consumes the authoritative server-computed initialData
 * generated by getHomepageInitialData() in src/lib/homepage-data.ts.
 *
 * It serves as a pure React Context provider without any independent client-side
 * data fetching, unverified filtering, or manual revenue reconstruction.
 */
export function StartupDataProvider({
  children,
  initialData,
}: {
  children: React.ReactNode;
  initialData?: HomepageInitialData | null;
}) {
  const value: StartupDataContextType = {
    leaderboard: initialData?.leaderboard ?? [],
    recentlyListedData: initialData?.recentlyListedData ?? [],
    trendingData: initialData?.trendingData ?? [],
    verifiedStartupCount: initialData?.verifiedStartupCount ?? 0,
    verifiedRevenueTotal: initialData?.verifiedRevenueTotal ?? 0,
    loading: false,
    error: null,
  };

  return (
    <StartupDataContext.Provider value={value}>
      {children}
    </StartupDataContext.Provider>
  );
}
